### PR TITLE
Handle multi-line strings sent to "open file" service

### PR DESCRIPTION
**Pull request by ghost**
I've added 2 functions, one to trim the strings (taken from ergoemacs,
but can possibly be rewritten) and one to wrap the current
"dnd-open-file" into a loop over the contents of the list since it can
only accept 1 path argument at a time.

### CODE REVIEW

**Comment by davidswelt** [comment]
Thank you.  I have merged this.

**Comment by ghost** [comment]
Are there chances this ns-win.el modification makes it to the original ns-win.el? Is there anything I can do about that?

**Comment by davidswelt** [comment]
You mean, the original Emacs?
I can do that when I get around to it.  Ping me in a month or so.

**Comment by ghost** [comment]
I follow emacs-devel, I can check with them.

Jean-Christophe

**Comment by ghost** [comment]
I've copied the code I got committed to Emacs HEAD but I can't seem to find a way to make a pull request on a "child" of a previously made pull request...

**Comment by davidswelt** [comment]
The easiest would be to back out the previous change and then cherry-pick the change from the Emacs branch.

**Comment by ghost** [comment]
You can't just pull the code from my fork and merge it ? I still have issues understanding how git(hub) works so I my be asking the wrong question...

**Pull request merged**
