### PR TITLE
Limit action to libgnutls and dependencies. Print beter details.

### PR DESCRIPTION
**Pull request by treese**
This version prints better information about the dependencies used, and also will only process libgnutls and its dependencies. We can update the script in the future to allow any others we need.

### CODE REVIEW

**Comment by davidswelt** [comment]
I'm merging this for now so we make progress here, but I find it strange you would punt if there are other libraries present on the build machine.  I'd think you should just not touch these libraries if that is the case... What is the reasoning here?

**Comment by treese** [comment]
I may have misunderstood what you wanted. If grabbing any referenced libraries from homebrew on the build machine is fine with you, it's fine with me, and I can take out the limit to gnutls. The rebuilding of libraries would still remain under your separate control, of course, so that nothing gets updated automatically.

**Comment by davidswelt** [comment]
Yes, perhaps there is a misunderstanding.

Here is my suggestion:

(1) Do copy the ones that are necessary to run the binary, because it references them (and output which they are).  We must assume that we are legal to redistribute them.

(2) Do not update anything unless a specific update command is given — updating should not be part of the build process.

(3) Additional libraries that need to be copied should not cause the build process to be aborted.


How do you feel about that?

**Comment by treese** [comment]
That sounds fine, and I'll make the changes. 

However, I'm not sure what you mean by point (3). Do you mean that libraries that don't have the right minimum version should not be copied, and that the script should print a warning about those without exiting with an error?

**Comment by davidswelt** [comment]
If I haven’t replied to that:

It seems that not copying them would produce a binary that is worse than one that is incompatible with older versions of the OS.
In fact, it would produce a binary that fails to run unless the libraries are present on the system.

On that basis, I guess the most prudent thing would be to continue the build and include those libraries (someone else might use the build script for local purposes), but print a warning at the end.

Alternatively, it might be safe to error out and refuse the build when that happens.  This is called from the build script, not “make”, so I’d be comfortable with that, too.

D

**Pull request merged**
