### PR TITLE
Fix fullscreen for OS X 10.7

### PR DESCRIPTION
**Pull request by eamsden**
Most apps allocate their own virtual screen when switching to full screen in Lion. Aquamacs takes over the desktop instead. This commit fixes this by setting the spaces-related window flag only on pre-Lion OSes, and only setting the Lion-related fullscreen flags when running on Lion.

This is my first attempt at hacking on an OS X app or in Objective-C, so feedback is welcomed.

### CODE REVIEW

**Comment by davidswelt** [comment]
Thanks, Ed.

We almost duplicated effort: I checked in a fix last night, and it is in the nightly builds by now.

That said, I think your patch may be sensible to use on top of my changes.  Can you merge them and see if it is necessary? 

Best,
- David

**Comment by eamsden** [comment]
Actually this pull request includes my merge of your fix it would appear (see commit 'Merge branch 'master') 
because I originally cloned my local repo from your github repo's public URL, and then switched the origin to my fork once I found a fix.

Currently this does actually break on 10.6.8 though, so I'm will see what I can do about that (it crashes on the call to toggleFullScreen). That was on a build that merged our changes. After work (in a few hours) I'll try it again with just my changes to narrow down what breaks.

**Comment by eamsden** [comment]
Looking at the code, toggleFullScreen shouldn't even be called on Snow Leopard, regardless of the changes I made, unless the compiler is optimizing away the respondsToSelector check. It does turn out that our changes are redundant though. I'll withdraw the pull request, but I'm going to verify that a build done on Lion will work on Snow Leopard still.

**Comment by davidswelt** [comment]
On Nov 11, 2011, at 3:52 PM, Edward Amsden wrote:

> Looking at the code, toggleFullScreen shouldn't even be called on Snow Leopard, regardless of the changes I made, unless the compiler is optimizing away the respondsToSelector check. It does turn out that our changes are redundant though. I'll withdraw the pull request, but I'm going to verify that a build done on Lion will work on Snow Leopard still.

The reason why that "respondsTo..." call doesn't work is, I think, that it may be called from EmacsFullWindow, which is a subclass of EmacsWindow.  So, "super" is then really the EmacsWindow object rather than the NSWindow one as intended.  I've now replaced it with a check of the Appkit version, because calling [NSWindow responseToSelector" somehow didn't work.

I've just verified that the 10.5 builds also work on Lion as intended; I don't have a 10.6 system here just now to check that, but I'm pretty confident there won't be a problem.
- David

PS.: You're more than welcome to join aquamacs-devel.  I'd be interested in contributions from you - other features of Lion (like auto-restore and document versioning) seem deserving of integration, too.

## 

http://aquamacs.org -- Aquamacs: Emacs on Mac OS X
http://aquamacs.org/donate -- Could we help you? Return the favor and support the Aquamacs Project!

**Comment by davidswelt** [comment]
A number of people have remarked that the fullscreen mode in Aquamacs doesn't conform to the way applications in Lion usually interact with spaces when using fullscreen mode, among other related issues.

These problems have been resolved as far as I can tell with an update I have made to the 2.x and 3.x branches:

http://aquamacs.org/nightlies.shtml

Feel free to have a look and report back about your experience.  And to those who wrote: thanks for getting in touch.

## 

http://aquamacs.org -- Aquamacs: Emacs on Mac OS X
http://aquamacs.org/donate -- Could we help you? Return the favor and support the Aquamacs Project!

**Comment by eamsden** [comment]
I'd be happy to join aquamacs-devel. I don't have an easy way to make sure my patches work on older versions of OS X, though.

**Comment by davidswelt** [comment]
Great, and no worries about compatibility issues, I'll help out with that.  Just be aware that it may take a bit of reworking of each patch before it can go in, simply because it isn't straightforward to make things work reliably for a lot of different users.
- d

**Pull request closed without merging**
